# Generated by Django 3.1.7 on 2021-04-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanime_app', '0009_merge_20210406_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fav_list',
            new_name='favList',
        ),
    ]
