# Generated by Django 3.1.7 on 2021-04-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanime_app', '0010_auto_20210406_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favList',
        ),
        migrations.AddField(
            model_name='favlist',
            name='user_fav',
            field=models.ManyToManyField(to='fanime_app.Profile'),
        ),
    ]
