# Generated by Django 3.1.7 on 2021-04-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanime_app', '0013_auto_20210406_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
