# Generated by Django 3.1.6 on 2021-04-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanime_app', '0018_merge_20210408_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='api_img',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
