# Generated by Django 3.1.7 on 2021-04-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanime_app', '0006_auto_20210405_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavAnime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_link', models.CharField(max_length=100)),
                ('api_id', models.CharField(max_length=10)),
                ('api_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
