# Generated by Django 3.1.6 on 2021-04-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanime_app', '0007_auto_20210405_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav_anime_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav_anime_name',
        ),
    ]
