# Generated by Django 3.1.7 on 2021-04-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanime_app', '0008_auto_20210405_2320'),
        ('fanime_app', '0008_auto_20210406_1302'),
    ]

    operations = [
    ]
