# Generated by Django 3.1.7 on 2021-04-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanime_app', '0012_auto_20210406_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favList',
            new_name='fav_list',
        ),
    ]
