# Generated by Django 3.1.6 on 2021-04-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanime_app', '0016_auto_20210406_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='api_link',
        ),
    ]
