# Generated by Django 3.1.7 on 2021-04-07 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanime_app', '0017_auto_20210407_2103'),
        ('fanime_app', '0017_remove_anime_api_link'),
    ]

    operations = [
    ]
