# Generated by Django 3.1.7 on 2021-04-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanime_app', '0021_auto_20210407_2324'),
        ('fanime_app', '0019_anime_api_img'),
    ]

    operations = [
    ]
